---
# This is the top-level playbook that defines our entire infrastructure.

- hosts: all
  user: deploy
  become: True
  gather_facts: True

  roles:
    - common
    - blog
    - mailserver
    - webmail
    - news
    - nextcloud
    - gitea
    - ircbouncer
    - xmpp
    - matrix
    - mastodon
    - vpn
    - monitoring  # Monitoring role should be last. See roles/monitoring/README.md
